// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "go-api/definitions/model"

	mock "github.com/stretchr/testify/mock"

	request "go-api/definitions/request"

	response "go-api/definitions/response"
)

// Comment is an autogenerated mock type for the Comment type
type Comment struct {
	mock.Mock
}

// ListRequestToFilter provides a mock function with given fields: req
func (_m *Comment) ListRequestToFilter(req request.CommentList) model.CommentFilter {
	ret := _m.Called(req)

	var r0 model.CommentFilter
	if rf, ok := ret.Get(0).(func(request.CommentList) model.CommentFilter); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(model.CommentFilter)
	}

	return r0
}

// ModelToListResponse provides a mock function with given fields: _a0
func (_m *Comment) ModelToListResponse(_a0 []model.Comment) response.CommentList {
	ret := _m.Called(_a0)

	var r0 response.CommentList
	if rf, ok := ret.Get(0).(func([]model.Comment) response.CommentList); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(response.CommentList)
		}
	}

	return r0
}

// ModelToResponse provides a mock function with given fields: _a0
func (_m *Comment) ModelToResponse(_a0 model.Comment) response.Comment {
	ret := _m.Called(_a0)

	var r0 response.Comment
	if rf, ok := ret.Get(0).(func(model.Comment) response.Comment); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(response.Comment)
	}

	return r0
}

type mockConstructorTestingTNewComment interface {
	mock.TestingT
	Cleanup(func())
}

// NewComment creates a new instance of Comment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewComment(t mockConstructorTestingTNewComment) *Comment {
	mock := &Comment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
