// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Blog is an autogenerated mock type for the Blog type
type Blog struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx
func (_m *Blog) Create(ctx *gin.Context) {
	_m.Called(ctx)
}

// Delete provides a mock function with given fields: ctx
func (_m *Blog) Delete(ctx *gin.Context) {
	_m.Called(ctx)
}

// List provides a mock function with given fields: ctx
func (_m *Blog) List(ctx *gin.Context) {
	_m.Called(ctx)
}

// Update provides a mock function with given fields: ctx
func (_m *Blog) Update(ctx *gin.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewBlog interface {
	mock.TestingT
	Cleanup(func())
}

// NewBlog creates a new instance of Blog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBlog(t mockConstructorTestingTNewBlog) *Blog {
	mock := &Blog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
